openapi: "3.0.0"
components:
  schemas:
    Chassis:
      $ref: ./Chassis.yaml#/components/schemas/Chassis_Chassis
    ServiceRoot:
      $ref: ./ServiceRoot.yaml#/components/schemas/ServiceRoot_ServiceRoot
    Storage:
      $ref: ./Storage.yaml#/components/schemas/Storage_Storage
    StorageCollection:
      $ref: ./StorageCollection.yaml#/components/schemas/StorageCollection_StorageCollection
    StoragePool:
      $ref: ./StoragePool.yaml#/components/schemas/StoragePool_StoragePool
    StoragePoolCollection:
      $ref: ./StoragePoolCollection.yaml#/components/schemas/StoragePoolCollection_StoragePoolCollection
    Volume:
      $ref: ./Volume.yaml#/components/schemas/Volume_Volume
    VolumeCollection:
      $ref: ./VolumeCollection.yaml#/components/schemas/VolumeCollection_VolumeCollection
