image: golang:1.21-alpine

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - checkstyle
  - test
  - build

before_script:
  - mkdir -p /go/src/gitlab.com/IgorNikiforov /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/IgorNikiforov/swordfish-emulator-go
  - ln -s /go/src/gitlab.com/IgorNikiforov /go/src/gitlab.com/IgorNikiforov
  - adduser testuser -D
  - cd /go/src/gitlab.com/IgorNikiforov/swordfish-emulator-go
  - chmod 777 -R ./

lint_code:
  stage: checkstyle
  script:
    - ./scripts/lint.sh

unit_tests:
  stage: test
  coverage: /\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)/
  script:
    - su - testuser -c 'export PATH=$PATH:/usr/local/go/bin; cd /go/src/gitlab.com/IgorNikiforov/swordfish-emulator-go && go test -cover ./... -tags=unit -covermode=count -coverprofile=coverage.out'
    - go tool cover -func coverage.out

build:
  stage: build
  script:
    - go build -v ./...
