// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/IgorNikiforov/swordfish-emulator-go/internal/service (interfaces: ServiceRootService,StorageService,StorageCollectionService)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination mock/mock_service.go . ServiceRootService,StorageService,StorageCollectionService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	domain "gitlab.com/IgorNikiforov/swordfish-emulator-go/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceRootService is a mock of ServiceRootService interface.
type MockServiceRootService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRootServiceMockRecorder
}

// MockServiceRootServiceMockRecorder is the mock recorder for MockServiceRootService.
type MockServiceRootServiceMockRecorder struct {
	mock *MockServiceRootService
}

// NewMockServiceRootService creates a new mock instance.
func NewMockServiceRootService(ctrl *gomock.Controller) *MockServiceRootService {
	mock := &MockServiceRootService{ctrl: ctrl}
	mock.recorder = &MockServiceRootServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRootService) EXPECT() *MockServiceRootServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceRootService) Create(arg0 context.Context, arg1 *domain.ServiceRootV1161ServiceRoot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockServiceRootServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceRootService)(nil).Create), arg0, arg1)
}

// Get mocks base method.
func (m *MockServiceRootService) Get(arg0 context.Context, arg1 string) (*domain.ServiceRootV1161ServiceRoot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*domain.ServiceRootV1161ServiceRoot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceRootServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceRootService)(nil).Get), arg0, arg1)
}

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStorageService) Get(arg0 context.Context, arg1 string) (*domain.StorageV1151Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*domain.StorageV1151Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageService)(nil).Get), arg0, arg1)
}

// Replace mocks base method.
func (m *MockStorageService) Replace(arg0 context.Context, arg1 string, arg2 *domain.StorageV1151Storage) (*domain.StorageV1151Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.StorageV1151Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockStorageServiceMockRecorder) Replace(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockStorageService)(nil).Replace), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockStorageService) Update(arg0 context.Context, arg1 string, arg2 []byte) (*domain.StorageV1151Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.StorageV1151Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStorageServiceMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorageService)(nil).Update), arg0, arg1, arg2)
}

// MockStorageCollectionService is a mock of StorageCollectionService interface.
type MockStorageCollectionService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageCollectionServiceMockRecorder
}

// MockStorageCollectionServiceMockRecorder is the mock recorder for MockStorageCollectionService.
type MockStorageCollectionServiceMockRecorder struct {
	mock *MockStorageCollectionService
}

// NewMockStorageCollectionService creates a new mock instance.
func NewMockStorageCollectionService(ctrl *gomock.Controller) *MockStorageCollectionService {
	mock := &MockStorageCollectionService{ctrl: ctrl}
	mock.recorder = &MockStorageCollectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageCollectionService) EXPECT() *MockStorageCollectionServiceMockRecorder {
	return m.recorder
}

// AddStorage mocks base method.
func (m *MockStorageCollectionService) AddStorage(arg0 context.Context, arg1 string, arg2 *domain.StorageV1151Storage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStorage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStorage indicates an expected call of AddStorage.
func (mr *MockStorageCollectionServiceMockRecorder) AddStorage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStorage", reflect.TypeOf((*MockStorageCollectionService)(nil).AddStorage), arg0, arg1, arg2)
}

// DeleteStorage mocks base method.
func (m *MockStorageCollectionService) DeleteStorage(arg0 context.Context, arg1 string) (*domain.StorageV1151Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStorage", arg0, arg1)
	ret0, _ := ret[0].(*domain.StorageV1151Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStorage indicates an expected call of DeleteStorage.
func (mr *MockStorageCollectionServiceMockRecorder) DeleteStorage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStorage", reflect.TypeOf((*MockStorageCollectionService)(nil).DeleteStorage), arg0, arg1)
}

// Get mocks base method.
func (m *MockStorageCollectionService) Get(arg0 context.Context, arg1 string) (*domain.StorageCollectionStorageCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*domain.StorageCollectionStorageCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageCollectionServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageCollectionService)(nil).Get), arg0, arg1)
}
