db:
  host: "localhost:5432"
  name: "emulator"
  user: "pguser"
  password: "pgpwd"
embedded-psql:
  name: "emulator"
  port: 5432
  username: "pguser"
  password: "pgpwd"
  version: "V13.8"
  data-path: "./.persist"
dataset:
  path: "./datasets/basic"
  overwrite: true
server:
  host: ":8080"
  write-timeout: 15s
  read-timeout: 15s
